name = "Bapanada"
author = "Mercy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e959b42ba3764fb51855c7168c307d6a5d3636ba83152744473e13e95dcc4fef"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
