name = "Bapanada"
author = "Mercy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "29b1ac891237203cf57221ae8c3083de9e8a6a6bd366386a9645e1c8bfdc480c"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
