name = "Bapanada"
author = "Mercy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ed09d4703bd1f7a9443a354a8be5a12e56dbc87f21af5cb1d84f51ad43a9d3ec"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
